#################################################################################
# FreeFlyer Runtime API                                                         #
# Copyright a.i. solutions, Inc.                                                #
#                                                                               #
# This file is a part of the FreeFlyer Runtime API distribution and you are     #
# free to modify this item or use it in its current form for your own projects. #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES      #
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF              #
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR       #
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES        #
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN         #
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF       #
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                #
#                                                                               #
#################################################################################
# This file was auto-generated by rtapi_code_generator. Do not manually edit
# except for local testing because those edits will be overwritten.
# aisolutions.freeflyer.runtimeapi package
"""
    Contains a class which holds Runtime API function ids.
"""

class FunctionId:
    """
        An enumeration representing the Runtime API functions.
    """

    Undefined = 0
    GetResultDescription = 1
    GetRuntimeApiVersion = 2
    GetFreeFlyerVersion = 3
    CreateEngine = 4
    CreateEngineWithOutputWindowSupport = 84
    DestroyEngine = 5
    KillEngine = 6
    IsEngineIdle = 7
    GetConsoleOutput = 8
    FreeMemory = 9
    LoadMissionPlanFromFile = 10
    LoadMissionPlanFromFileAsync = 11
    LoadMissionPlanFromFileDynamicAsync = 12
    LoadMissionPlanFromString = 13
    LoadMissionPlanFromStringAsync = 14
    LoadMissionPlanFromStringDynamicAsync = 15
    LoadFreeFlyerScriptFromFile = 16
    LoadFreeFlyerScriptFromFileAsync = 17
    LoadFreeFlyerScriptFromFileDynamicAsync = 18
    LoadFreeFlyerScriptFromFile2 = 87
    LoadFreeFlyerScriptFromFile2Async = 88
    LoadFreeFlyerScriptFromFile2DynamicAsync = 89
    LoadFreeFlyerScriptFromString = 19
    LoadFreeFlyerScriptFromStringAsync = 20
    LoadFreeFlyerScriptFromStringDynamicAsync = 21
    LoadFreeFlyerScriptFromString2 = 90
    LoadFreeFlyerScriptFromString2Async = 91
    LoadFreeFlyerScriptFromString2DynamicAsync = 92
    SetUserInfoArguments = 22
    SetUserInfoArgumentsAsync = 23
    SetUserInfoArgumentsDynamicAsync = 24
    PrepareMissionPlan = 25
    PrepareMissionPlanAsync = 26
    CleanupMissionPlan = 27
    CleanupMissionPlanAsync = 28
    ExecuteStatement = 29
    ExecuteStatementAsync = 30
    ExecuteRemainingStatements = 31
    ExecuteRemainingStatementsAsync = 32
    ExecuteUntilApiLabel = 33
    ExecuteUntilApiLabelAsync = 34
    ExecuteUntilApiLabelDynamicAsync = 35
    IsMissionPlanComplete = 36
    GetExecutionNumber = 37
    GetLocation = 38
    GetMissionPlanDiagnostics = 39
    EvaluateExpression = 40
    EvaluateExpressionAsync = 41
    AssignExpression = 85
    AssignExpressionAsync = 86
    AssignExpressionReference = 116
    AssignExpressionReferenceAsync = 117
    GetExpressionVariable = 42
    GetExpressionVariableAsync = 43
    GetExpressionArray = 44
    GetExpressionArrayAsync = 45
    GetExpressionMatrix = 46
    GetExpressionMatrixAsync = 47
    GetExpressionTimeSpan = 93
    GetExpressionTimeSpanAsync = 94
    GetExpressionTimeSpanArray = 95
    GetExpressionTimeSpanArrayAsync = 96
    GetExpressionString = 48
    GetExpressionStringAsync = 49
    GetExpressionStringArray = 50
    GetExpressionStringArrayAsync = 51
    SetExpressionVariable = 52
    SetExpressionVariableAsync = 53
    SetExpressionVariableDynamicAsync = 54
    SetExpressionArray = 55
    SetExpressionArrayAsync = 56
    SetExpressionArrayDynamicAsync = 57
    SetExpressionMatrix = 58
    SetExpressionMatrixAsync = 59
    SetExpressionMatrixDynamicAsync = 60
    SetExpressionTimeSpan = 97
    SetExpressionTimeSpanAsync = 98
    SetExpressionTimeSpanDynamicAsync = 99
    SetExpressionTimeSpanArray = 100
    SetExpressionTimeSpanArrayAsync = 101
    SetExpressionTimeSpanArrayDynamicAsync = 102
    SetExpressionString = 61
    SetExpressionStringAsync = 62
    SetExpressionStringDynamicAsync = 63
    SetExpressionStringArray = 64
    SetExpressionStringArrayAsync = 65
    SetExpressionStringArrayDynamicAsync = 66
    AllocateAsyncData = 67
    FreeAsyncData = 68
    SetAsyncDataVariable = 69
    SetAsyncDataArray = 70
    SetAsyncDataMatrix = 71
    SetAsyncDataTimeSpan = 103
    SetAsyncDataTimeSpanArray = 104
    SetAsyncDataString = 72
    SetAsyncDataStringArray = 73
    GetAsyncDataVariable = 74
    GetAsyncDataArray = 75
    GetAsyncDataMatrix = 76
    GetAsyncDataTimeSpan = 105
    GetAsyncDataTimeSpanArray = 106
    GetAsyncDataString = 77
    GetAsyncDataStringArray = 78
    IsValidTimeSpan = 107
    IsUndefinedTimeSpan = 108
    CompareTimeSpans = 109
    AddTimeSpans = 110
    SubtractTimeSpans = 111
    ScaleTimeSpan = 112
    GetUndefinedTimeSpan = 113
    GetTimeSpanAsSeconds = 114
    GetTimeSpanAsDays = 115
    Synchronize = 79
    SetSyncPointAsync = 80
    WaitForSyncPointAsync = 81
    WaitForAnySyncPointAsync = 82
    WaitForAllSyncPointsAsync = 83
